### ISSUE TITLE
Remplacer le logo en format svg dans la top bar

### ISSUE THREAD

**Issue by s2f2** [jbgariel/the-ds-interview#16]
cf slack

**Comment by jbgariel** [comment]
Est-ce que c'est utile ? vu que c'est juste du texte ça ne change pas grand chose.

Par contre il faudrait un logo.ico pour le logo de l'onglet (un petit du coup)

**Comment by s2f2** [comment]
Vu en call : il faut un logo pour fonds blancs et un logo fonds sombres

**Comment by s2f2** [comment]
cf Slack room design

**Comment by jbgariel** [comment]
done - tu peux checker les couleurs par page ?
