### ISSUE TITLE
Ajouter favicone

### ISSUE THREAD

**Issue by s2f2** [jbgariel/the-ds-interview#19]

**Comment by s2f2** [comment]
cf. Slack room design

**Comment by jbgariel** [comment]
done

**Comment by s2f2** [comment]
Je l'ai pas sous Chrome...
![image](https://user-images.githubusercontent.com/13719029/27150005-de88a064-5145-11e7-9547-e218769f9c3d.png)

**Comment by jbgariel** [comment]
En reloadant normalement, ou tu peux vider le cache je pense que c'est ça.

(tu cliques droit, "inspect" => onglet "Network" => "disable cache" 

la tu reloads (en gardant le slider "inspect" ouvert)

Dis moi si ça marche

**Comment by s2f2** [comment]
ca marche sur IE mais pas sur chrome ca doit etre un pb de cache
