### ISSUE TITLE
Ecrire les tags HTML meta

### ISSUE THREAD

**Issue by s2f2** [jbgariel/the-ds-interview#23]

**Comment by s2f2** [comment]
Est-ce que tu peux mettre ca entre les balises <head> de la home :

`<title>The Data Science Interview - Your data interview training platform.</title><meta name="description" content="Train and rock your next data science interview with 1000+ questions sourced from top firms hiring in data science. For free."><meta property="og:title" content="The Data Science Interview - Your data interview training platform."/><meta property="og:type" content="website"/><meta property="og:image" content="INSERT URL HERE"/><meta property="og:url" content="http:www.thedsinterview.com"/><meta property="og:description" content="Train and rock your next data science interview with 1000+ questions sourced from top firms hiring in data science. For free."/>`

Et mettre remplacer le "INSERT URL HERE" par l'url de l'image que j'ai mis dans Slack?

**Comment by jbgariel** [comment]
seems to work now
