### ISSUE TITLE
Changer typo home

### ISSUE THREAD

**Issue by s2f2** [jbgariel/the-ds-interview#43]
Sur les textes : 
Test your data science knowledge in real conditions by answering 1000+ actual interview questions.
Access a handful set of data science resources from top blogs to industry recognized newsletters.
Our job board aggregate data science job requisitions from some of the best companies in the world.
You are a recruiter and you want to reach thousands of top data scientists? Advertise on our site.

Mettre poppins light plutot que poppins regular

**Comment by s2f2** [comment]
c'est peut etre deja le cas, tell me

**Comment by jbgariel** [comment]
Mis en `font-weight: 100;` au lieu de 300

**Comment by s2f2** [comment]
very nice
